import {
  LayoutDashboard,
  Users,
  User,
  ClipboardList,
  Eye,
  Package,
  FileText,
  Pill,
  Printer,
  ScanLine,
  Database,
  Bell,
  Clock,
  BarChart2,
  BarChart3,
  MessageCircle,
  LogOut,
  X,
  ChevronRight,
  ChevronLeft,
  Edit,
  Lock,
} from "lucide-react";

const Icons = {
  Dashboard: LayoutDashboard,
  Users: Users,
  User: User,
  Orders: ClipboardList,
  TrackOrder: Eye,
  Refills: Package,
  Forms: FileText,
  Prescription: Pill,
  Fax: Printer, // Changed from Send to Printer for better representation
  Scanner: ScanLine,
  DataFetch: Database,
  Queue: Bell,
  Activity: Clock,
  Reports: BarChart2,
  BarChart3: BarChart3,
  Messages: MessageCircle, // Changed from MessageSquare to MessageCircle for distinction
  Logout: LogOut,
  Close: X,
  Expand: ChevronRight,
  Collapse: ChevronLeft,
  Edit: Edit,
  Lock: Lock,
};

export default Icons;
